### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Alnarra** [MysticMods/Roots#319]
https://paste.dimdev.org/alozecucuz.mccrash

Relevant 

```
// I let you down. Sorry :(

Time: 2019-10-06 15:18:54 EDT
Description: Initializing game

java.lang.NoClassDefFoundError: epicsquid/mysticalworld/materials/Materials
    at epicsquid.roots.init.ModVillagers.onProfessionRegister(ModVillagers.java:40)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_293_ModVillagers_onProfessionRegister_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: epicsquid.mysticalworld.materials.Materials
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 17 more
```

**Comment by Davoleo** [comment]
Might be an outdated dependency issue
try updating all mystic mods to the latest version

**Comment by duely** [comment]
Yeah, make sure you have 1.4.5 of Mystical World and 1.3.8 of MysticaLib. For some reason it doesn't do version enforcement this early.

**Comment by Alnarra** [comment]
Ah yes I see it, for whatever reason the Mystical world update didn't get picked up and was at 1.4.4. Update to 1.4.5 corrected the matter.

**Comment by duely** [comment]
Unfortunately the loader has to get through the whole process of loading, which is problematic when there are new classes, before it gets to the error message of "Hey, you, update! It needs version XYZ but you only have whatever!"
